#!/usr/bin/env python
import numpy as np
import dynaphopy.analysis.fitting as fitting
input_file = open("../test/correlation.out", "r")
#input_file = open("wave-X-320k.out","r")

initial_data = []

for line in input_file:
    initial_data.append(line.split())
initial_data = np.array(initial_data,dtype=float)

degeneracy =[[4, 5, 6]]

test_frequencies_range = np.array(initial_data[:,0])
data = []
for phonon in degeneracy:
    data_temp = np.zeros_like(test_frequencies_range)
    for degenerate in phonon:
        data_temp += initial_data[:, degenerate]
    data.append(data_temp)

data = np.array(data).T


fitting.phonon_fitting_analysis(data, test_frequencies_range)


